spring:
  application:
    name: app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem